name: Daily Commit

on:
  schedule:
    - cron: '10 5 * * *'  # Runs daily at 05:10 UTC (change as needed)
  workflow_dispatch:      # Enables manual trigger too

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name "GitHub Action Bot"
          git config user.email "24f1001750@ds.study.iitm.ac.in"

      - name: Daily commit step by 24f1001750@ds.study.iitm.ac.in
        run: |
          echo "Updated on $(date)" >> daily-log.txt
          git add daily-log.txt
          git commit -m "Daily update: $(date)" || echo "Nothing to commit"
          git push
